### ISSUE TITLE
DX: Create (guest) template for Rust to Wasm modules/functions

### ISSUE THREAD

**Issue by bdehaynin** [ipvm-wg/homestar#130]
# Summary

Template path for generating dependencies/needs for writing/wiring Rust → Wasm functions and compiling to the `wasm32-unknown-unknown` target.

## Components

- [ ] Either as an extension to https://github.com/fission-codes/rust-template, as a different path through the generator, or as a separate `cargo-generate` project. 
- [ ] TBD

This gives developers a way to more easily integrate with [wit-bindgen](https://github.com/bytecodealliance/wit-bindgen) and other `stdlib` features we would want to add over time. 

ETA: 2023-12-20

**Comment by zeeshanlakhani** [comment]
Closing at this has ties to #533.
