### ISSUE TITLE
Upstream change: Add ansi logs feature to EmbarkStudios/tracing-logfmt

### ISSUE THREAD

**Issue by zeeshanlakhani** [ipvm-wg/homestar#143]
### Summary

For dev/debug-mode(s), we should add upstream support for ANSI codes to define log-levels and keys (for logfmt). 

Lib: https://github.com/EmbarkStudios/tracing-logfmt. 

As per Embark's discord:

> Hey! This lib is just a pure logfmt implementation, without any bells and whistles, so no coloring support. The aim for us is to use it with Loki (and I think parsing using LogQL would not work well if there where ANSI escape sequences) But if you want to add coloring support, that would be welcomed, as long as it is optional and doens't pull in a crazy amount of dependencies.

The change would be a simple update to the write (and feature-flagging), akin to our custom layer in the rust-template: https://github.com/fission-codes/rust-template/blob/main/rust/src.axum/tracing_layers/format_layer.rs, particularly akin to https://github.com/fission-codes/rust-template/blob/main/rust/src.axum/tracing_layers/format_layer.rs#L251. 

Rather than main a custom layer, it'd be nice to use this functionality and update the upstream codebase.

**Comment by zeeshanlakhani** [comment]
@euamcg has a PR out: https://github.com/EmbarkStudios/tracing-logfmt/pull/11.

**Comment by euamcg** [comment]
Added in: https://github.com/EmbarkStudios/tracing-logfmt/pull/11
