### ISSUE TITLE
DX: Early Wasm Modules/Functions for Registry

### ISSUE THREAD

**Issue by zeeshanlakhani** [ipvm-wg/homestar#146]
# Summary

As we begin prototyping interesting example workflows and use cases with an IPVM registry, we need to create some basic functions/modules that can be chained together. 

## Examples

- [ ] Write an markdown => html (and/or other formats) converter
- [ ] Write a CSV <=> [Parquet](https://parquet.apache.org/) converter
- [ ] TBD?

**Comment by expede** [comment]
Jeff is also going to research high value use cases that should go in a standard lib

**Comment by zeeshanlakhani** [comment]
Closing, as everyCLI/where is tackling this.
