### ISSUE TITLE
Support rendezvous protocol for discovery

### ISSUE THREAD

**Issue by zeeshanlakhani** [ipvm-wg/homestar#214]
# Summary

Add support for https://docs.libp2p.io/concepts/discovery-routing/rendezvous/. This can be combined with our use of pubsub/gossipsub, as peer can be discovered based on listening on the same topic. 

## Solution

Can be based on examples, e.g.: https://github.com/libp2p/rust-libp2p/tree/master/examples/rendezvous.

**Comment by mriise** [comment]
Running rendezvous with the one provided by rust-libp2p doesn't run through pubsub, it is more of a fediverse-style where everyone can be their own server and everyone is their own client as well. IMO this approach should be more reliable since gossips isn't depending on itself to get its own peers.

**Comment by zeeshanlakhani** [comment]
> Running rendezvous with the one provided by rust-libp2p doesn't run through pubsub, it is more of a fediverse-style where everyone can be their own server and everyone is their own client as well. IMO this approach should be more reliable since gossips isn't depending on itself to get its own peers.

The combined note, just comes from the docs more explicitly:

```For effective discovery, rendezvous can be combined with [libp2p publish/subscribe](https://docs.libp2p.io/concepts/pubsub/overview). At a basic level, rendezvous can bootstrap pubsub by discovering peers subscribed to a topic. The rendezvous would be responsible for publishing packets, subscribing, or unsubscribing from packet shapes.```

**Comment by zeeshanlakhani** [comment]
Great work @mriise, thank you!
