### ISSUE TITLE
Phase 0: MVP

### ISSUE THREAD

**Issue by expede** [ipvm-wg/homestar#322]
## Description

Final components of the original MVP work on Homestar.

---

Children:
- [ ] https://github.com/ipvm-wg/homestar/issues/61
- [x] https://github.com/ipvm-wg/homestar/issues/276

Note: This roadmap is subject to change as priorities and circumstances evolve.

[Starmap Link ⭐️🗺️](https://starmap.site/roadmap/github.com/ipvm-wg/Homestar/issues/322)

ETA: 2023-10-20

**Comment by zeeshanlakhani** [comment]
Moving the last item over to Phase 1 and closing this out.
