### ISSUE TITLE
Running websocket-relay doesn't work if you already have IPFS running

### ISSUE THREAD

**Issue by bmann** [ipvm-wg/homestar#348]
I have IPFS Desktop running which runs a kubo instance locally

If I have kubo running and run the `cargo run -- start -c config/settings.toml` command as listed in [examples/websocket-relay](https://github.com/ipvm-wg/homestar/blob/main/examples/README.md) it doesn't work.

Recommendation:
* if we're going to puppet kubo like this we should use the not-default-port
* future: config option for people to run a binary of their choice / port of their choice (and even with examples, I'd rather us start leaning into iroh here)

**Comment by zeeshanlakhani** [comment]
Closed by #352
