### ISSUE TITLE
Update Fission logo on readme

### ISSUE THREAD

**Issue by chadkoh** [ipvm-wg/homestar#354]
# Summary

## Problem

Logo on the readme has been refreshed

## Solution

Replace with one of the selection in https://drive.google.com/drive/u/1/folders/1GoDU4-hlMBlEjGV4LME1syk2EXGgc-Gm

# Detail

**Describe the bug**

**Comment by zeeshanlakhani** [comment]
@chadkoh we should just move to the homestar logo right?
