### ISSUE TITLE
💫🇹🇷 Homestar Istanbul Workshop Tracking

### ISSUE THREAD

**Issue by expede** [ipvm-wg/homestar#406]
[Starmap 🌟🗺️](https://starmap.site/roadmap/github.com/ipvm-wg/homestar/issues/406?crumbs=%5B%5B%22fission-codes%2Feverywhere-computer-control-panel%2311%22%2C%22High+Level+Istanbul+Workshop+Starmap%22%5D%5D#view=simple)

Children:

- #407
- #390
- #131

ETA: 2023-11-10

**Comment by zeeshanlakhani** [comment]
Closing this now that we're done.
