### ISSUE TITLE
make homestar-runtime npm package follow crate version

### ISSUE THREAD

**Issue by hugomrdias** [ipvm-wg/homestar#468]
make the default npm tag follow rust and pin the binaries also to the same version.

- [x] sync versions with homestar-runtime wrapper: https://www.npmjs.com/package/homestar-runtime

**Comment by zeeshanlakhani** [comment]
@hugomrdias yeah. I will be working on this in the next couple (as we split the crates out). We need to case on the other condition here, right?

**Comment by hugomrdias** [comment]
right now its using the `cargo-get` thing we can keep that for the RCs but for production we should we the event tag.
we gonna need another job to release the wrapper package .ie `homestar-runtime` the CI only has jobs for the `homestar-<os>-<arch>`

**Comment by zeeshanlakhani** [comment]
yep. the tag is available from the release event.

**Comment by zeeshanlakhani** [comment]
Ah ok. @hugomrdias when we get to that, we can create another job.

**Comment by zeeshanlakhani** [comment]
@hugomrdias we can close this yeah?
